Aggiunta stile aziendale
FIUP/work_plan_template pull request #4
Opened 2018-04-28 16:28 UTC by fedsib

### Descrizione delle modifiche

Aggiunta degli stili per la personalizzazione di header/footer di ciascuna pagina.
Stili correntemente supportati:

- **Stile UNIPD**: Attivo di default, è il classico stile unipd con nell'header logo unipd, ragione sociale dell'azienda, dati studente (nome, cognome, matricola tra parentesi tonde). Nel footer è riportato solo il numero di pagine attuale, rapportato al totale.

- **Stile Aziendale**: Nell' header riporta il logo aziendale sulla sinistra, la ragione sociale e il sito internet; nel footer i dati aziendali (Ragione sociale, indirizzo e sito internet) sulla sinistra, al centro il numero di pagine attuale, rapportato al totale e a destra i dati aziendali di contatto (telefono del tutor aziendale, email, Partita IVA)

**Aggiunti nuovi comandi**
\emailAzienda
\partitaIVAAzienda

### Design Alternativi

### Benefici

### Possibili regressioni

### Issue coinvolte

2018-04-29 14:37 UTC, sydernee requested changes
In linea di massima è ok, eccetto i punti segnalati.  👍

2018-04-29 14:37 UTC, sydernee commented on README.md
> +Il seguente template serve per creare un file `.pdf` contenente il piano di lavoro dello studente ma per essere ufficialmente approvato,potrebbe essere necessario stamparlo su carta intestata dell'az
Manca lo spazio prima della frase "potrebbe essere necessario".

2018-04-29 14:37 UTC, sydernee commented on README.md
> +1. **Stile Unipd**: Nell'header compare Il logo Unipd, i dati dello studente (nome, cognome e matricola, la ragione sociale dell'azienda dove si fa lo stage).
"Nell'header compare Il logo Unipd" vs "Nell'header compare: Il logo aziendale": nel primo caso si è deciso di mettere i due punti, nel secondo no.

2018-04-29 14:37 UTC, sydernee commented on Template/Layout.tex
> +\usepackage[italian]{babel}
Conviene mettere, in ordine:
1. fontenc
2. inputenc
3. babel

Mentre l'ordine dei primi due mi sembra già meno scontato, direi che babel [sicuramente va per terzo](https://guitex.org/home/en/forum/5-tex-e-latex/70373-inputenc-e-fontenc-quale-dei-due-prima).

L'ordine corrisponde alle iniziali di Federazione Italiana Basket. :D (fontenc, inputenc, babel)

2018-04-29 18:24 UTC, fedsib reviewed
Corretto ordine dei pacchetti e fix dei typo.

2018-05-20 14:38 UTC, fedsib commented
@sydernee Spostato hyperref come ultimo package come richiesto.

2018-05-20 19:53 UTC, merged